# -*- coding: utf-8 -*-
"""yeehacks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5ePaCgovpRx-vLLSVGyR892mzOc0SkK
"""

!nvidia-smi

!pip install inference
!pip install roboflow

# from roboflow import Roboflow

# rf = Roboflow(api_key="CpI5R2UCAvEVdyRHU7x5")
# project = rf.workspace("taco-ihjgk").project("yolov8-trash-detections-kgnug")
# model = project.version(9).model

!pip install flask flask-cors pyngrok

from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok
from roboflow import Roboflow
import tempfile, os

app = Flask(__name__)
CORS(app)

rf = Roboflow(api_key="CpI5R2UCAvEVdyRHU7x5")
project = rf.workspace("taco-ihjgk").project("yolov8-trash-detections-kgnug")
model = project.version(11).model

@app.route("/detect", methods=["POST"])
def detect():
    file = request.files["image"]

    # Save temp file
    with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as tmp:
        file.save(tmp.name)
        result = model.predict(tmp.name, confidence=40).json()
        os.unlink(tmp.name)

    predictions = result["predictions"]
    if not predictions:
        return jsonify({"error": "No trash detected"})

    # Return the top detected item
    top = max(predictions, key=lambda x: x["confidence"])
    return jsonify({
        "class": top["class"],
        "confidence": round(top["confidence"] * 100, 1)
    })

ngrok.set_auth_token("3BGLk25H0MvHTw5RMK1zMLVvw8n_66hBs8nRWMWsTnKDgyggY")

# Start ngrok tunnel
public_url = ngrok.connect(5000)
print(f"Backend URL: {public_url}")

app.run(port=5000)